on:
  workflow_dispatch:
  issues:
    types: [edited]

jobs:
  edit_issue:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: print
        run: |
          # 変数定義
          id='${{ github.event.issue.number }}'
          title='${{ github.event.issue.title }}'
          body='${{ github.event.issue.body }}'

          # 整形
          _body=${body}
          _body=${_body//$'\r\n'/\\n}
          _body=${_body//$'\n'/\\n}
          echo ${title}
          echo ${_body}

          # 新規記事生成
          touch ./_posts/${id}.md
          echo "---" >>./_posts/${id}.md
          echo "title: ${title}" >>./_posts/${id}.md
          echo "---" >>./_posts/${id}.md
          echo "${body}" >>./_posts/${id}.md
      - name: push
        run: |
          git add .
          git commit -m "add: new blog"
          git push origin master
