name: 記事更新

on:
  workflow_dispatch:
  issues:
    types: [opened, edited]

jobs:
  edit_issue:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: print
        run: |
          # 変数定義
          created_at='${{ github.event.issue.created_at }}'
          id='${{ github.event.issue.number }}'
          title='${{ github.event.issue.title }}'
          body='${{ github.event.issue.body }}'
          # 整形
          _body=${body}
          _body=${_body//$'\r\n'/\\n}
          _body=${_body//$'\n'/\\n}
          echo ${title}
          echo ${_body}
          # 新規記事生成
          if [ ! -d ./_posts ]; then
            mkdir ./_posts
          fi
          if [ -f ./_posts/${id}.md ]; then
            rm ./_posts/${id}.md
          fi
          touch ./_posts/${id}.md
          echo "---" >>./_posts/${id}.md
          echo "title: '${title}'" >>./_posts/${id}.md
          echo "date: '${created_at}'" >>./_posts/${id}.md
          echo "---" >>./_posts/${id}.md
          echo "${body}" >>./_posts/${id}.md
      - name: push
        run: |
          git config user.name  "admin"
          git config user.email "action@github.com"
          git add .
          git commit -m "add: new blog"
          git pull
          git push origin master

  build:
    needs: edit_issue
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '19.x'
          cache: npm

      - name: Prepare
        run: git pull

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # - name: Move 404 to root
      #   run: mv ./out/404/index.html ./out/404.html

      - name: Deploy
        uses: actions/upload-pages-artifact@v1
        with:
          path: out

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
